# $NetBSD$

PKGNAME=	php-test-${PHP_BASE_VERS}
CATEGORIES=	lang

MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	PHP test package

META_PACKAGE=	yes

PHP_VERSIONS_ACCEPTED=		${PHP_VERSION_DEFAULT}

.include "../../lang/php/phpversion.mk"
.include "${PHPPKGSRCDIR}/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
